### ISSUE TITLE
[FEAT] - Build out tests

### ISSUE THREAD

**Issue by nhcarrigan** [nhcarrigan/Becca-Lyria#199]
# Feature Request

## Is your feature request related to a problem? Please describe:

With #198 landing, it looks like we have a successful framework for adding tests. I'd like to see if we can get some tests built for the other commands, so we can start leveraging the CI to verify the commands work.

## Describe the solution you'd like

Tests can be added in individual PRs for each command, or if someone feels ambitious they can be done all at once.

**Comment by adprasad** [comment]
hey @nhcarrigan , I'd be happy to add some more test probably best if its done one command at a time since i don't know the functionality a well plus it would give others an opportunity to try adding some tests too.

If thats alright, i'll start with the about command and if someone wants to add tests for another command they can just say which one they want to add tests for.

**Comment by nhcarrigan** [comment]
Feel free to poke away at it as you can!

**Comment by adprasad** [comment]
Adding tests for help command

**Comment by adprasad** [comment]
Adding tests for invite command

**Comment by adprasad** [comment]
Adding tests for the listeners command

**Comment by adprasad** [comment]
Adding tests for privacy command

**Comment by adprasad** [comment]
Adding tests for art command

**Comment by adprasad** [comment]
Adding tests for `games/dnd` command. Since these are related I may try to get everything under the folder at once.

**Comment by adprasad** [comment]
Adding tests for `games/hp` command. Since these are related I may try to get everything under the folder at once.
